apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: worth-it-api-xyz-tls
spec:
  secretName: worth-it-api-xyz
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: worth-it-api.xyz 
  dnsNames:
    - worth-it-api.xyz 
    - www.worth-it-api.xyz 
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - worth-it-api.xyz 
          - www.worth-it-api.xyz 