apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  tls:
    - hosts:
        - worth-it-api.xyz 
        - www.worth-it-api.xyz 
      secretName: worth-it-api-xyz
  rules:
    - host: worth-it-api.xyz
      http:
        paths:
          # - path: /?(.*)
          - path: /
            backend:
              serviceName: client-cluster-ip-service
              servicePort: 3000
          # - path: /api/?(.*)
          - path: /api/
            backend:
              serviceName: server-cluster-ip-service
              servicePort: 5000
    - host: www.worth-it-api.xyz
      http:
        paths:
          # - path: /?(.*)
          - path: /
            backend:
              serviceName: client-cluster-ip-service
              servicePort: 3000
          # - path: /api/?(.*)
          - path: /api/
            backend:
              serviceName: server-cluster-ip-service
              servicePort: 5000